[package]
name = "rtcli"
version = "0.2.0"
edition = "2024"
repository = "https://github.com/angularbanjo/rtcli"
license = "Apache-2.0"
description = "Modern, portable rtorrent CLI"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
comfy-table = "7"
terminal_size = "0.4"
unicode-width = "0.2"
thiserror = "2"
toml = "0.8"
dirs = "5"
base64 = "0.22"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
